### ISSUE TITLE
backendとfrontendのCIを作る

### ISSUE THREAD

**Issue by Tatsumi0000** [Tatsumi0000/starry-kids#5]
### 💪 やること
- backendとfrontendのCI環境を作る。
  - RailsとVueです。
- backendはminimagickを使っているのでimagemagickが必要です。そのため、普通の`setup/ruby`みたいなやつを使っていると面倒です。なのでgithubにDocker Imageをアップしてそれを使ってテストを回すようにします。
  - Docker Imageは、 `web/backend/Dockerfile`に変更が加わる && masterブランチだと自動でCDするようにします。
  - DockerHubだとRateLimitにかかるかもなので、GitHub Packagesを使います。
- 高速にCIを回したいのでキャッシュの設定を入れます。

### ✅ 解決したいこと
- railsのCI環境ほしい
- VueのCI環境ほしい

### 🥅 このissueのゴール
- railsのCI環境ができる
- RailsのCIで使うDocker ImageをGitHub PackagesにCDできる

**Comment by Tatsumi0000** [comment]
- docker の仕様でリポジトリ名に大文字は含んではダメです。
- ghcr.ioにpushしたい場合は権限を付与してあげる必要があるみたいです。
  - 
```
Error: buildx failed with: ERROR: denied: installation not allowed to Create organization package
```
リポジトリのsettingsから↓の設定に変更したら動き出しました。

<img width="796" alt="Screenshot 2023-10-01 at 4 36 29" src="https://github.com/Tatsumi0000/starry-kids/assets/19218690/6649253b-a83e-4396-b2f8-8b10e1df6d88">

**Comment by Tatsumi0000** [comment]
モノレポ構成なので特定のディレクトリのみ持ってきたいです。その時は、`sparse-checkout`を使うといい。

```yml
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            web/backend
```

ref.
- [スパースチェックアウトでチェックアウトするパスを指定する](https://tech.guitarrapc.com/entry/2023/06/15/000000#GitHub-Actions-%E3%81%A7%E3%82%B9%E3%83%91%E3%83%BC%E3%82%B9%E3%83%81%E3%82%A7%E3%83%83%E3%82%AF%E3%82%A2%E3%82%A6%E3%83%88%E3%82%92%E4%BD%BF%E3%81%86)

**Comment by Tatsumi0000** [comment]
`actions/cache@v3`を使う時にcontainer上で色々やってるときは少し設定が必要です。
↓みたいなWaringが出てきます。

```
Warning: Path Validation Error: Path(s) specified in the action for caching do(es) not exist, hence no cache is being saved.
```

どうやら、`actions/cache@v3`はコンテナ内を見れないので、指定したキャッシュ対象のディレクトリを見れないっぽいです。そのため、[jobs.<job_id>.container.volumes](https://docs.github.com/ja/actions/using-jobs/running-jobs-in-a-container#mounting-volumes-in-a-container)を使ってGitHub Actionsのランナーにマウントする必要があります。
`volumes`が大事です。あとマウントするときはhost側が相対パスでコンテナが絶対パスじゃないとダメです。

```yml
jobs:
  backend-ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web/backend

    container:
      image: ghcr.io/tatsumi0000/starry-kids/backend:latest
      # volumesを設定しないとactions/cacheがコンテナ内を見れない
      volumes:
        - ./vendor/bundle:/usr/src/app/backend/vendor/bundle
```


<details>
    <summary>相対パスと絶対パスで指定してない時にでてきたエラー</summary>


  Error: Exit code 1 returned from process: file name '/usr/bin/docker', arguments 'create --name 00e874316d6541fbb22e5f7af65aed4f_ghcriotatsumi0000starrykidsbackendlatest_26ab72 --label 94351b --workdir /__w/starry-kids/starry-kids --network github_network_44349c04ab7a4597ae3c4c5e5a11c0ab  -e "HOME=/github/home" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "./vendor/bundle":"./vendor/bundle" -v "/home/runner/work":"/__w" -v "/home/runner/runners/2.309.0/externals":"/__e":ro -v "/home/runner/work/_temp":"/__w/_temp" -v "/home/runner/work/_actions":"/__w/_actions" -v "/opt/hostedtoolcache":"/__t" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" --entrypoint "tail" ghcr.io/tatsumi0000/starry-kids/backend:latest "-f" "/dev/null"'.

</details>
